# Generated by Django 4.1.2 on 2023-04-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_category_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='referencia',
            field=models.CharField(default='referencia', max_length=255),
        ),
    ]
