# Generated by Django 4.1.2 on 2023-04-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0006_alter_post_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='referencia',
            field=models.TextField(),
        ),
    ]
